version: '3.8'

networks:
  newsforyou:

services:
  news-app:
    container_name: news-app-container
    image: news-app:0.1
    restart: on-failure
    build:
      context: ./
    ports:
      - 3000:3000
    networks:
      - newsforyou

